### ISSUE TITLE
Policy ui IDE plugin

### ISSUE THREAD

**Issue by kazvictor** [ca-api-gateway/gateway-developer-plugin#103]

**Comment by amoghsa** [comment]
@kazvictor, any specific IDE in your mind? IntelliJ or Eclipse?

**Comment by kazvictor** [comment]
It should be implemented in an IDE agnostic way as much as possible. There should be initial support for either Intellij or Eclipse and support for both eventually.

**Comment by joao-borges** [comment]
Tracked internally by [F81667](https://rally1.rallydev.com/#/56296273706d/detail/portfolioitem/feature/270989000404)
