### ISSUE TITLE
In the GatewayConnection use a default localhost url if one is not provided

### ISSUE THREAD

**Issue by kazvictor** [ca-api-gateway/gateway-developer-plugin#120]
In nearly all cases the `url` in the Gateway connection will be `https://localhost:8443/restman`. Make this the default if a url is not set.

**Comment by yves-chan** [comment]
I thought that https://localhost:8443/restman is already the default from CAGatewayExport#setDefaults(GatewayConnectionProperties)

**Comment by joao-borges** [comment]
@kazvictor I tested here and Yves is correct, if not set the default is used, so I think this is not necessary.

**Comment by kazvictor** [comment]
you are right, it is! Closing this issue.
