### ISSUE TITLE
`BundleLoadException: Multiple l7:ResourceSet elements found` exporting SOAP service

### ISSUE THREAD

**Issue by kazvictor** [ca-api-gateway/gateway-developer-plugin#126]
**Describe the bug**
Create a soap service using policy manager (You can use any wsdl)

**To Reproduce**
1. Create a soap service using policy manager (You can use any wsdl)
2. Export a solution that contains this service
3. See the following error:
    * `BundleLoadException: Multiple l7:ResourceSet elements found` 

**Expected behavior**
Should have successfully exported

**Comment by amoghsa** [comment]
Initial investigation shows that, a normal policy has only one resourceset under resources element, but for SOAP services, we have 2. One for policy and other for wsdl file itself. Does that mean, we should implement another EntityLoader for SOAP based services?

**Comment by amoghsa** [comment]
Another sub class won't help, because we differentiate based on L7:type value from bundle. Only distinguishing factor between normal service and SOAP service is value of l7:Property key="soap". Based on this, we need to create separate path for soap service and other service.
