### ISSUE TITLE
Sonar Cloud plugin for Policy style checks

### ISSUE THREAD

**Issue by kazvictor** [ca-api-gateway/gateway-developer-plugin#134]
There was a project called Apollo that performed style and flow checks on policy. Use the idea's behind the Apollo project to create a Sonar Cloud plugin that will perform checks on policy. https://docs.sonarqube.org/display/PLUG/Plugin+Library

I would be able to run something like:
```./gradlew check```
This should then return policy style checks and warnings. 
I should also be able to setup a build that will send the policy to sonar cloud for validation.

**Comment by joao-borges** [comment]
Tracked internally by [F81666](https://rally1.rallydev.com/#/56296273706d/detail/portfolioitem/feature/270987396980)
