### ISSUE TITLE
Add support for Import into Appliance Gateways

### ISSUE THREAD

**Issue by kazvictor** [ca-api-gateway/gateway-developer-plugin#140]
In general the plugins should work without change when exporting from an appliance Gateway. However we need a procedure on how we can import bundles that are built by the plugins into appliance Gateways.
Some things that this could involve:
* documentation on how to use restman to import a bundle into an appliance gateway
* enable an environment bundle to be built by calling a task in the gradle plugins.

**Comment by joao-borges** [comment]
Basic steps documented in https://github.com/ca-api-gateway-examples/gateway-developer-example/blob/master/deployment/build.gradle
