### ISSUE TITLE
Replace Wsdl content from services.xml with path to actual wsdl file

### ISSUE THREAD

**Issue by amoghsa** [ca-api-gateway/gateway-developer-plugin#146]
**Describe the bug**
There is one thing missing from Soap service export, currently it stores wsdl file in services.xml, but this xml should be moved to separate file and mention path in services.xml
Possible placement for wsdl file:
1) Create `wsdl` folder in `developer-example` under `src/main/gateway`
2) Create `wsdl` folder under `src/main/gateway/policy/path to policy/`
3) Add it in same place where policy is residing?

**Comment by joao-borges** [comment]
Tracked internally by [US573807](https://rally1.rallydev.com/#/56296273706d/detail/userstory/287005671700?fdp=true)
