### ISSUE TITLE
UMLs or data flow diagram for Dev plugin

### ISSUE THREAD

**Issue by amoghsa** [ca-api-gateway/gateway-developer-plugin#182]

**Comment by amoghsa** [comment]
Add gliffy diagrams to [wiki](https://cawiki.ca.com/display/AG/Gateway+Developer+Plugin)
1) flow of data from module to module
2) detailed data flow with most common use case like policy export-build with 1 environment property

**Comment by joao-borges** [comment]
Tracked internally by [US573761](https://rally1.rallydev.com/#/56296273706d/detail/userstory/286948318140).
